# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Apple Watch Info
email:            contact@applewatch.info
description:      The Latest Apple Watch News and Information
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://applewatch.info' # The base hostname & protocol for your site
github_username:
twitter_username: applewatchdot

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Jon:
    name: Jon Lawrence
    display_name: Jon Lawrence
    bio: Just a guy that loves his Apple Watch
    gravatar: https://1.gravatar.com/avatar/a8dd3eceb108cca9eb3b318068fcc188?s=96&d=mm&r=g
    email: contact@applewatch.info
    website: https://applewatch.info
    github_username:
    twitter_username: jonecat
